version: '2'
services:
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - /var/opt/mongo:/data/db
  java-app:
    build: .
    command: java -jar target/java-mongo-0.0.1-SNAPSHOT-jar-with-dependencies.jar
    links:
     - mongo
